{
    "item1":{"asunto":"El Destino", "url":"https://youtu.be/_bEK7f_B1pM?t=1330"},
    "item2":{"asunto":"La Tierra", "url":"https://youtu.be/_bEK7f_B1pM?t=1485"},
    "item3":{"asunto":"El Hombre", "url":"https://youtu.be/_bEK7f_B1pM?t=1537"},
    "item4":{"asunto":"Urano", "url":"https://youtu.be/_bEK7f_B1pM?t=1690"},
    "item":{"asunto":"Saturno", "url":"https://youtu.be/_bEK7f_B1pM?t=1829"},
    "item":{"asunto":"Saturno Encarnado - Edad de Oro - Comunismo - Saturnales - Carnaval", "url":"https://youtu.be/_bEK7f_B1pM?t=1943"},
    "item":{"asunto":"Saturno - Cronos - Tiempo - Muerte", "url":"https://youtu.be/_bEK7f_B1pM?t=2089"},
    "item":{"asunto":"Saturno - Esposa Rea Cibeles- Hijos", "url":"https://youtu.be/_bEK7f_B1pM?t=2223"},
    "item":{"asunto":"Rea Cibeles", "url":"https://youtu.be/_bEK7f_B1pM?t=2249"},
    "item":{"asunto":"El Olimpo", "url":"https://youtu.be/_bEK7f_B1pM?t=2661"},
    "item":{"asunto":"Júpiter", "url":"https://youtu.be/_bEK7f_B1pM?t=2875"},
    "item":{"asunto":"Júpiter Vs Saturno - Rescate a sus hermanos", "url":"https://youtu.be/_bEK7f_B1pM?t=2965"},
    "item":{"asunto":"Júpiter - Esposas e Hijos", "url":"https://youtu.be/_bEK7f_B1pM?t=3237"},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""},
    "item":{"asunto":"", "url":""}
}
